In [51]:
import numpy as np
h = np.array([[-1], [-1], [-1]])
h

array([[-1],
       [-1],
       [-1]])

In [52]:
J = np.array([[0, -1.5, 0.5], [-1.5, 0, 0], [0.5, 0, 0]])
J

array([[ 0. , -1.5,  0.5],
       [-1.5,  0. ,  0. ],
       [ 0.5,  0. ,  0. ]])

In [53]:
H = np.hstack([h, J])
H

array([[-1. ,  0. , -1.5,  0.5],
       [-1. , -1.5,  0. ,  0. ],
       [-1. ,  0.5,  0. ,  0. ]])

In [54]:
hamiltonian_data = {
  "data": [{"i": 0,"j": 0,"val": -1},
    {"i": 1,"j": 0,"val": -1},
    {"i": 2,"j": 0,"val": -1,},
    {"i": 0,"j": 2,"val": -1.5},
    {"i": 0, "j": 3,"val": 0.5},
    {"i": 1,"j": 1,"val": -1.5},
    {"i": 2,"j": 1,"val": 0.5}],
  "file_name": "simple_hamiltonian.json", # can be any short string
  "num_variables": 3, # number of rows
  "file_type": "hamiltonian" # defines the data type as hamiltonian
}
hamiltonian_data

{'data': [{'i': 0, 'j': 0, 'val': -1},
  {'i': 1, 'j': 0, 'val': -1},
  {'i': 2, 'j': 0, 'val': -1},
  {'i': 0, 'j': 2, 'val': -1.5},
  {'i': 0, 'j': 3, 'val': 0.5},
  {'i': 1, 'j': 1, 'val': -1.5},
  {'i': 2, 'j': 1, 'val': 0.5}],
 'file_name': 'simple_hamiltonian.json',
 'num_variables': 3,
 'file_type': 'hamiltonian'}

In [55]:
import qci_client as qc
qci = qc.qci_client.QciClient(api_token="M3YYWg1ZaEuWkKI2eCIxFaFMoKeYem5m", url="https://api.qci-next.com")

In [56]:
response_json = qci.upload_file(hamiltonian_data)

In [60]:
job_params_instance = {"sampler_type": "eqc2", "n_samples": 2, "solution_type": "integer", "debug": True}

In [61]:
job_json = qci.build_job_body(
    job_type="sample-hamiltonian",
    job_params=job_params_instance,
    hamiltonian_file_id=response_json["file_id"]) 

In [62]:
job_response = qci.process_job(job_body=job_json, job_type="sample-hamiltonian")

Job submitted job_id='64dd4343f25d8eafde6e4f61'-: 2023/08/16 21:44:35
RUNNING: 2023/08/16 21:44:36
COMPLETED: 2023/08/16 21:45:18


In [63]:
results = job_response['results']
print(results['energies'][0])  # first entry, lowest energy
print(results['samples'][0]) # prints first solution array
sample = np.array(results["samples"][0]) # populates lowest energy sample into   a numpy array .

-7600
[63, 63, 0]
